channels:
- conda-forge
dependencies:
- python=3.8.10
- pip
- pip:
  - mlflow
  - boto3==1.16.7
  - cffi==1.14.5
  - keras==2.8.0
  - pandas==1.2.4
  - pillow==8.2.0
  - scipy==1.6.2
  - tensorflow==2.8.0
name: mlflow-env
